[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "vLTgeZhLgcr4HvBGxKonSnmU4t7qLcgsVcVtUd3haZc"

[programs.mainnet]
amm = "3bt3f7BRg7zTZL8LbVTa5QeoD29Svd8t1L3xGwrjgmgz"
futarchy = "D2E45PQk715zosJaJcwauGP5PiyBipYQpNqsCrQMGMWV"
vault = "vLTgeZhLgcr4HvBGxKonSnmU4t7qLcgsVcVtUd3haZc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = ".keys/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
