[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
amm = "AMMSgtnttAKx5Ad2Y1socKJ3CcQYCB2ctg8U2SAHcVEx"
futarchy = "FUTKPrt66uGGCTpk6f9tmRX2325cWgXzGCwvWhyyzjea"
svault = "SVLTnMmZLkY5bCJbRgYdSABQNW14qfy5ZWhmEcASGx3"
vault = "VLTEetGyPKtffi1u3Jr8btWATv33NeDyUuRsPENFPTU"

[programs.localnet]
amm = "AMMSgtnttAKx5Ad2Y1socKJ3CcQYCB2ctg8U2SAHcVEx"
futarchy = "FUTKPrt66uGGCTpk6f9tmRX2325cWgXzGCwvWhyyzjea"
svault = "SVLTnMmZLkY5bCJbRgYdSABQNW14qfy5ZWhmEcASGx3"
vault = "VLTEetGyPKtffi1u3Jr8btWATv33NeDyUuRsPENFPTU"

[programs.mainnet]
amm = "AMMSgtnttAKx5Ad2Y1socKJ3CcQYCB2ctg8U2SAHcVEx"
futarchy = "FUTKPrt66uGGCTpk6f9tmRX2325cWgXzGCwvWhyyzjea"
svault = "SVLTnMmZLkY5bCJbRgYdSABQNW14qfy5ZWhmEcASGx3"
vault = "VLTEetGyPKtffi1u3Jr8btWATv33NeDyUuRsPENFPTU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".keys/authority.json"

[scripts]
prop = "./scripts/sync-idl.sh"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
test-amm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/amm/**/*.ts\""
test-dao = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/dao/**/*.ts\""
test-fut = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/futarchy/**/*.ts\""
test-vault = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/vault/**/*.ts\""
